### ISSUE TITLE
First time running the photowall

### ISSUE THREAD

**Issue by Newman5** [colbyfayock/photowall#1]
First - Colby, you are a champion for making this.  I wanted to give feedback on how I started it up.  

These are the 'issues' i came across:
1
PUBLIC_CLOUDINARY_CLOUD_NAME?  
I get this error when running npm run dev

```
Missing PUBLIC_CLOUDINARY_CLOUD_NAME. Please set it as an environment variable inside of your .env.
  Stack trace:
    at eval ... blah blah ... content-layer.js:138:5)
    ```
    I'm going to change what's in the repo from NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME 
    to 
PUBLIC_CLOUDINARY_CLOUD_NAME

remove the NEXT_... and that worked.

2

> ┃ Local    http://localhost:4321/
> ┃ Network  use --host to expose
> 
> 15:09:03 [content] Syncing content
> 15:09:04 [cloudinary-assets-loader] Loading Cloudinary Assets
> 15:09:04 [ERROR] [cloudinary-assets-loader] Error: Failed to list resources.
> 15:09:04 [watch] .astro/assets.mjs

Where am I suppose to put the folders in Cloudinary?  

> To start using Photowall, create a new folder called photowall in your Cloudinary account.
> 
> Inside, create 1 or more folders to create new collections. Drop your images inside each collection to create a new gallery!
> 
> To further configure your gallery, create a config.json file and place it inside of a collection directory, with the structure of:

My question is:  how do I create a config.json file inside the collection directory in my cloudinary account?

looking around now...

**Comment by colbyfayock** [comment]
hey sorry for the confusion
- it used to be a Next.js project, i missed some spots to update the instructions
- you have to create a config.json file outside of Cloudinary then drop it in so it retains the config.json name

i'll work on updating these instructions to make it more clear

**Comment by Newman5** [comment]
oh!  hey ya.  Thanks for the response.  If you need a tester, I'm here to help.  I think this could a real benefit for simply sharing photos.  Right now I'm using Flickr but would rather it be stored on cloudinary and then displayed on my own site.  

![image](https://github.com/user-attachments/assets/6e292fdd-409f-44d0-ba2e-1b3fc5fb111a)
this was my latest error.

Cheers,
n

**Comment by Newman5** [comment]
Just working with your video, I started from scratch and came up with this - https://newman5.github.io/photocloud/

I'm pretty happy I could do it.  It really is simple!  I'm hoping to play around with more use case for the content layer.  cheers and thanks for your inspiration and help

**Comment by colbyfayock** [comment]
nice one!

**Comment by colbyfayock** [comment]
fixed the .env.example and updated the documentation to be a little more clear. thanks for the feedback
